### ISSUE TITLE
Examples in use?

### ISSUE THREAD

**Issue by l-acs** [hectorespert/jlibnotify#60]
Hi there!

I just stumbled across this and am very interested; I've been looking for something like this for a while. I noticed it's in active development so I thought I'd leave a note. Are there any projects using this that I could take a look at? I know some people are great at figuring this stuff out without documentation, but unfortunately I am not one of those people.... but I was thinking an example would be enough.

Thanks for your time and for your effort into making this!

**Comment by hectorespert** [comment]
> Thanks for your time and for your effort into making this!

Thank you!

There aren't many projects. The main project is [https://github.com/hectorespert/nb-native-notifications](https://github.com/hectorespert/nb-native-notifications)

Other example is: https://github.com/mediathekview/MediathekView
